/* Generated by tools/gen_vectors.py from the conformance vectors.
   Do not edit; run `make gen` to regenerate. */

static void cf_decode(void) {
  { /* simple-table */
    const unsigned char v1[] = {0x1d,0x75,0x73,0x65,0x72,0x73,0x01,0x6e,0x61,0x6d,0x65,0x1f,0x61,0x6d,0x6f,0x75,0x6e,0x74,0x1e,0x41,0x6c,0x69,0x63,0x65,0x1f,0x31,0x30,0x30,0x1e,0x42,0x6f,0x62,0x1f,0x32,0x30,0x30};
    const unsigned char v2[1] = {0};
    CHECK(cf_eq(c0_doc_name(v1,36), v2, 0));
    { c0_doc_iter di = c0_doc(v1, 36); c0_group g;
      CHECK(c0_next_group(&di,&g));
      const unsigned char v3[] = {0x75,0x73,0x65,0x72,0x73};
      CHECK(cf_eq(c0_group_name(g), v3, 5));
      { c0_iter hi = c0_group_headers(g); c0_bytes h;
        const unsigned char v4[] = {0x6e,0x61,0x6d,0x65};
        CHECK(c0_next_header(&hi,&h) && cf_eq(h,v4,4));
        const unsigned char v5[] = {0x61,0x6d,0x6f,0x75,0x6e,0x74};
        CHECK(c0_next_header(&hi,&h) && cf_eq(h,v5,6));
        CHECK(!c0_next_header(&hi,&h)); }
      { c0_iter ri = c0_group_records(g); c0_bytes rec;
        CHECK(c0_next_record(&ri,&rec));
        CHECK(cf_arity(rec)==2);
        const unsigned char v6[] = {0x41,0x6c,0x69,0x63,0x65};
        CHECK(cf_val_eq(rec,0,v6,5));
        const unsigned char v7[] = {0x31,0x30,0x30};
        CHECK(cf_val_eq(rec,1,v7,3));
        CHECK(c0_next_record(&ri,&rec));
        CHECK(cf_arity(rec)==2);
        const unsigned char v8[] = {0x42,0x6f,0x62};
        CHECK(cf_val_eq(rec,0,v8,3));
        const unsigned char v9[] = {0x32,0x30,0x30};
        CHECK(cf_val_eq(rec,1,v9,3));
        CHECK(!c0_next_record(&ri,&rec)); }
      CHECK(!c0_next_group(&di,&g)); }
  }
  { /* trailing-us-empty-field */
    const unsigned char v10[] = {0x1e,0x41,0x6c,0x69,0x63,0x65,0x1f};
    c0_group g = c0_table(v10, 7);
    const unsigned char v11[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v11, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==2);
      const unsigned char v12[] = {0x41,0x6c,0x69,0x63,0x65};
      CHECK(cf_val_eq(rec,0,v12,5));
      const unsigned char v13[1] = {0};
      CHECK(cf_val_eq(rec,1,v13,0));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* leading-us-empty-field */
    const unsigned char v14[] = {0x1e,0x1f,0x61};
    c0_group g = c0_table(v14, 3);
    const unsigned char v15[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v15, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==2);
      const unsigned char v16[1] = {0};
      CHECK(cf_val_eq(rec,0,v16,0));
      const unsigned char v17[] = {0x61};
      CHECK(cf_val_eq(rec,1,v17,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* empty-middle-field */
    const unsigned char v18[] = {0x1e,0x61,0x1f,0x1f,0x63};
    c0_group g = c0_table(v18, 5);
    const unsigned char v19[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v19, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==3);
      const unsigned char v20[] = {0x61};
      CHECK(cf_val_eq(rec,0,v20,1));
      const unsigned char v21[1] = {0};
      CHECK(cf_val_eq(rec,1,v21,0));
      const unsigned char v22[] = {0x63};
      CHECK(cf_val_eq(rec,2,v22,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* empty-record-at-end */
    const unsigned char v23[] = {0x1e,0x61,0x1e};
    c0_group g = c0_table(v23, 3);
    const unsigned char v24[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v24, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v25[] = {0x61};
      CHECK(cf_val_eq(rec,0,v25,1));
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v26[1] = {0};
      CHECK(cf_val_eq(rec,0,v26,0));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* empty-record-between */
    const unsigned char v27[] = {0x1e,0x1e,0x62};
    c0_group g = c0_table(v27, 3);
    const unsigned char v28[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v28, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v29[1] = {0};
      CHECK(cf_val_eq(rec,0,v29,0));
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v30[] = {0x62};
      CHECK(cf_val_eq(rec,0,v30,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* escaped-us-in-value */
    const unsigned char v31[] = {0x1e,0x61,0x10,0x1f,0x62,0x1f,0x63};
    c0_group g = c0_table(v31, 7);
    const unsigned char v32[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v32, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==2);
      const unsigned char v33[] = {0x61,0x1f,0x62};
      CHECK(cf_val_eq(rec,0,v33,3));
      const unsigned char v34[] = {0x63};
      CHECK(cf_val_eq(rec,1,v34,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* escaped-dle */
    const unsigned char v35[] = {0x1e,0x10,0x10};
    c0_group g = c0_table(v35, 3);
    const unsigned char v36[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v36, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v37[] = {0x10};
      CHECK(cf_val_eq(rec,0,v37,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* escaped-binary-bytes */
    const unsigned char v38[] = {0x1e,0x10,0x00,0x10,0x06,0x10,0x1b};
    c0_group g = c0_table(v38, 7);
    const unsigned char v39[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v39, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v40[] = {0x00,0x06,0x1b};
      CHECK(cf_val_eq(rec,0,v40,3));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* nested-scope-us */
    const unsigned char v41[] = {0x1e,0x02,0x78,0x1f,0x79,0x03,0x1f,0x7a};
    c0_group g = c0_table(v41, 8);
    const unsigned char v42[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v42, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==2);
      const unsigned char v43[] = {0x02,0x78,0x1f,0x79,0x03};
      CHECK(cf_val_eq(rec,0,v43,5));
      const unsigned char v44[] = {0x7a};
      CHECK(cf_val_eq(rec,1,v44,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* bare-records */
    const unsigned char v45[] = {0x1e,0x61,0x1f,0x62,0x1e,0x63,0x1f,0x64};
    c0_group g = c0_table(v45, 8);
    const unsigned char v46[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v46, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==2);
      const unsigned char v47[] = {0x61};
      CHECK(cf_val_eq(rec,0,v47,1));
      const unsigned char v48[] = {0x62};
      CHECK(cf_val_eq(rec,1,v48,1));
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==2);
      const unsigned char v49[] = {0x63};
      CHECK(cf_val_eq(rec,0,v49,1));
      const unsigned char v50[] = {0x64};
      CHECK(cf_val_eq(rec,1,v50,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* multi-group-document */
    const unsigned char v51[] = {0x1c,0x64,0x62,0x1d,0x67,0x31,0x1e,0x61,0x1d,0x67,0x32,0x1e,0x62};
    const unsigned char v52[] = {0x64,0x62};
    CHECK(cf_eq(c0_doc_name(v51,13), v52, 2));
    { c0_doc_iter di = c0_doc(v51, 13); c0_group g;
      CHECK(c0_next_group(&di,&g));
      const unsigned char v53[] = {0x67,0x31};
      CHECK(cf_eq(c0_group_name(g), v53, 2));
      { c0_iter hi = c0_group_headers(g); c0_bytes h;
        CHECK(!c0_next_header(&hi,&h)); }
      { c0_iter ri = c0_group_records(g); c0_bytes rec;
        CHECK(c0_next_record(&ri,&rec));
        CHECK(cf_arity(rec)==1);
        const unsigned char v54[] = {0x61};
        CHECK(cf_val_eq(rec,0,v54,1));
        CHECK(!c0_next_record(&ri,&rec)); }
      CHECK(c0_next_group(&di,&g));
      const unsigned char v55[] = {0x67,0x32};
      CHECK(cf_eq(c0_group_name(g), v55, 2));
      { c0_iter hi = c0_group_headers(g); c0_bytes h;
        CHECK(!c0_next_header(&hi,&h)); }
      { c0_iter ri = c0_group_records(g); c0_bytes rec;
        CHECK(c0_next_record(&ri,&rec));
        CHECK(cf_arity(rec)==1);
        const unsigned char v56[] = {0x62};
        CHECK(cf_val_eq(rec,0,v56,1));
        CHECK(!c0_next_record(&ri,&rec)); }
      CHECK(!c0_next_group(&di,&g)); }
  }
  { /* utf8-value */
    const unsigned char v57[] = {0x1e,0x68,0xc3,0xa9,0x6c,0x6c,0x6f};
    c0_group g = c0_table(v57, 7);
    const unsigned char v58[1] = {0};
    CHECK(cf_eq(c0_group_name(g), v58, 0));
    { c0_iter hi = c0_group_headers(g); c0_bytes h;
      CHECK(!c0_next_header(&hi,&h)); }
    { c0_iter ri = c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v59[] = {0x68,0xc3,0xa9,0x6c,0x6c,0x6f};
      CHECK(cf_val_eq(rec,0,v59,6));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* etb-tolerated */
    const unsigned char v60[] = {0x1d,0x67,0x17,0x01,0x68,0x17,0x1e,0x61,0x17};
    const unsigned char v61[1] = {0};
    CHECK(cf_eq(c0_doc_name(v60,9), v61, 0));
    { c0_doc_iter di = c0_doc(v60, 9); c0_group g;
      CHECK(c0_next_group(&di,&g));
      const unsigned char v62[] = {0x67};
      CHECK(cf_eq(c0_group_name(g), v62, 1));
      { c0_iter hi = c0_group_headers(g); c0_bytes h;
        const unsigned char v63[] = {0x68};
        CHECK(c0_next_header(&hi,&h) && cf_eq(h,v63,1));
        CHECK(!c0_next_header(&hi,&h)); }
      { c0_iter ri = c0_group_records(g); c0_bytes rec;
        CHECK(c0_next_record(&ri,&rec));
        CHECK(cf_arity(rec)==1);
        const unsigned char v64[] = {0x61};
        CHECK(cf_val_eq(rec,0,v64,1));
        CHECK(!c0_next_record(&ri,&rec)); }
      CHECK(!c0_next_group(&di,&g)); }
  }
  { /* header-no-records */
    const unsigned char v65[] = {0x1d,0x67,0x01,0x61,0x1f,0x62};
    const unsigned char v66[1] = {0};
    CHECK(cf_eq(c0_doc_name(v65,6), v66, 0));
    { c0_doc_iter di = c0_doc(v65, 6); c0_group g;
      CHECK(c0_next_group(&di,&g));
      const unsigned char v67[] = {0x67};
      CHECK(cf_eq(c0_group_name(g), v67, 1));
      { c0_iter hi = c0_group_headers(g); c0_bytes h;
        const unsigned char v68[] = {0x61};
        CHECK(c0_next_header(&hi,&h) && cf_eq(h,v68,1));
        const unsigned char v69[] = {0x62};
        CHECK(c0_next_header(&hi,&h) && cf_eq(h,v69,1));
        CHECK(!c0_next_header(&hi,&h)); }
      { c0_iter ri = c0_group_records(g); c0_bytes rec;
        CHECK(!c0_next_record(&ri,&rec)); }
      CHECK(!c0_next_group(&di,&g)); }
  }
}

static void cf_encode(void) {
  { /* simple-table */
    c0_builder bld; c0_builder_init(&bld);
    const unsigned char v70[] = {0x75,0x73,0x65,0x72,0x73};
    c0_build_group(&bld,v70,5);
    const unsigned char v71[] = {0x6e,0x61,0x6d,0x65};
    const unsigned char v72[] = {0x61,0x6d,0x6f,0x75,0x6e,0x74};
    { c0_bytes H[] = {{v71,4},{v72,6}}; c0_build_headers(&bld,H,2); }
    const unsigned char v73[] = {0x41,0x6c,0x69,0x63,0x65};
    const unsigned char v74[] = {0x31,0x30,0x30};
    { c0_bytes F[] = {{v73,5},{v74,3}}; c0_build_record(&bld,F,2); }
    const unsigned char v75[] = {0x42,0x6f,0x62};
    const unsigned char v76[] = {0x32,0x30,0x30};
    { c0_bytes F[] = {{v75,3},{v76,3}}; c0_build_record(&bld,F,2); }
    const unsigned char v77[] = {0x1d,0x75,0x73,0x65,0x72,0x73,0x01,0x6e,0x61,0x6d,0x65,0x1f,0x61,0x6d,0x6f,0x75,0x6e,0x74,0x1e,0x41,0x6c,0x69,0x63,0x65,0x1f,0x31,0x30,0x30,0x1e,0x42,0x6f,0x62,0x1f,0x32,0x30,0x30};
    { c0_bytes got=c0_builder_bytes(&bld);
      CHECK(got.len==36 && (got.len==0||memcmp(got.ptr,v77,36)==0));
      CHECK(c0_canonical(got.ptr,got.len)); }
    c0_builder_free(&bld); }
  { /* escape-rs-in-value */
    c0_builder bld; c0_builder_init(&bld);
    const unsigned char v78[] = {0x67};
    c0_build_group(&bld,v78,1);
    const unsigned char v79[] = {0x61,0x1e,0x62};
    { c0_bytes F[] = {{v79,3}}; c0_build_record(&bld,F,1); }
    const unsigned char v80[] = {0x1d,0x67,0x1e,0x61,0x10,0x1e,0x62};
    { c0_bytes got=c0_builder_bytes(&bld);
      CHECK(got.len==7 && (got.len==0||memcmp(got.ptr,v80,7)==0));
      CHECK(c0_canonical(got.ptr,got.len)); }
    c0_builder_free(&bld); }
  { /* escape-newline-tab */
    c0_builder bld; c0_builder_init(&bld);
    const unsigned char v81[] = {0x67};
    c0_build_group(&bld,v81,1);
    const unsigned char v82[] = {0x6c,0x31,0x0a,0x6c,0x32,0x09,0x78};
    { c0_bytes F[] = {{v82,7}}; c0_build_record(&bld,F,1); }
    const unsigned char v83[] = {0x1d,0x67,0x1e,0x6c,0x31,0x10,0x0a,0x6c,0x32,0x10,0x09,0x78};
    { c0_bytes got=c0_builder_bytes(&bld);
      CHECK(got.len==12 && (got.len==0||memcmp(got.ptr,v83,12)==0));
      CHECK(c0_canonical(got.ptr,got.len)); }
    c0_builder_free(&bld); }
  { /* trailing-empty-field */
    c0_builder bld; c0_builder_init(&bld);
    const unsigned char v84[] = {0x67};
    c0_build_group(&bld,v84,1);
    const unsigned char v85[] = {0x61};
    const unsigned char v86[1] = {0};
    { c0_bytes F[] = {{v85,1},{v86,0}}; c0_build_record(&bld,F,2); }
    const unsigned char v87[] = {0x1d,0x67,0x1e,0x61,0x1f};
    { c0_bytes got=c0_builder_bytes(&bld);
      CHECK(got.len==5 && (got.len==0||memcmp(got.ptr,v87,5)==0));
      CHECK(c0_canonical(got.ptr,got.len)); }
    c0_builder_free(&bld); }
  { /* empty-record */
    c0_builder bld; c0_builder_init(&bld);
    const unsigned char v88[] = {0x67};
    c0_build_group(&bld,v88,1);
    const unsigned char v89[1] = {0};
    { c0_bytes F[] = {{v89,0}}; c0_build_record(&bld,F,1); }
    const unsigned char v90[] = {0x1d,0x67,0x1e};
    { c0_bytes got=c0_builder_bytes(&bld);
      CHECK(got.len==3 && (got.len==0||memcmp(got.ptr,v90,3)==0));
      CHECK(c0_canonical(got.ptr,got.len)); }
    c0_builder_free(&bld); }
  { /* binary-run */
    c0_builder bld; c0_builder_init(&bld);
    const unsigned char v91[] = {0x67};
    c0_build_group(&bld,v91,1);
    const unsigned char v92[] = {0x00,0x01,0x02,0x1f};
    { c0_bytes F[] = {{v92,4}}; c0_build_record(&bld,F,1); }
    const unsigned char v93[] = {0x1d,0x67,0x1e,0x10,0x00,0x10,0x01,0x10,0x02,0x10,0x1f};
    { c0_bytes got=c0_builder_bytes(&bld);
      CHECK(got.len==11 && (got.len==0||memcmp(got.ptr,v93,11)==0));
      CHECK(c0_canonical(got.ptr,got.len)); }
    c0_builder_free(&bld); }
  { /* high-bytes-unescaped */
    c0_builder bld; c0_builder_init(&bld);
    const unsigned char v94[] = {0x67};
    c0_build_group(&bld,v94,1);
    const unsigned char v95[] = {0x68,0xc3,0xa9,0x6c,0x6c,0x6f};
    { c0_bytes F[] = {{v95,6}}; c0_build_record(&bld,F,1); }
    const unsigned char v96[] = {0x1d,0x67,0x1e,0x68,0xc3,0xa9,0x6c,0x6c,0x6f};
    { c0_bytes got=c0_builder_bytes(&bld);
      CHECK(got.len==9 && (got.len==0||memcmp(got.ptr,v96,9)==0));
      CHECK(c0_canonical(got.ptr,got.len)); }
    c0_builder_free(&bld); }
  { /* file-two-groups */
    c0_builder bld; c0_builder_init(&bld);
    const unsigned char v97[] = {0x64,0x62};
    c0_build_file(&bld,v97,2);
    const unsigned char v98[] = {0x67,0x31};
    c0_build_group(&bld,v98,2);
    const unsigned char v99[] = {0x61};
    { c0_bytes F[] = {{v99,1}}; c0_build_record(&bld,F,1); }
    const unsigned char v100[] = {0x67,0x32};
    c0_build_group(&bld,v100,2);
    const unsigned char v101[] = {0x62};
    { c0_bytes F[] = {{v101,1}}; c0_build_record(&bld,F,1); }
    const unsigned char v102[] = {0x1c,0x64,0x62,0x1d,0x67,0x31,0x1e,0x61,0x1d,0x67,0x32,0x1e,0x62};
    { c0_bytes got=c0_builder_bytes(&bld);
      CHECK(got.len==13 && (got.len==0||memcmp(got.ptr,v102,13)==0));
      CHECK(c0_canonical(got.ptr,got.len)); }
    c0_builder_free(&bld); }
}

static void cf_canonical(void) {
  { /* minimal-escape */
    const unsigned char v103[] = {0x1e,0x61,0x10,0x1e,0x62};
    CHECK(cf_wellformed(v103,5)==1);
    CHECK(c0_canonical(v103,5)==1);
  }
  { /* plain-table */
    const unsigned char v104[] = {0x1d,0x75,0x73,0x65,0x72,0x73,0x01,0x6e,0x61,0x6d,0x65,0x1f,0x61,0x6d,0x6f,0x75,0x6e,0x74,0x1e,0x41,0x6c,0x69,0x63,0x65,0x1f,0x31,0x30,0x30,0x1e,0x42,0x6f,0x62,0x1f,0x32,0x30,0x30};
    CHECK(cf_wellformed(v104,36)==1);
    CHECK(c0_canonical(v104,36)==1);
  }
  { /* escaped-unassigned-byte */
    const unsigned char v105[] = {0x1e,0x10,0x06};
    CHECK(cf_wellformed(v105,3)==1);
    CHECK(c0_canonical(v105,3)==1);
  }
  { /* gratuitous-escape */
    const unsigned char v106[] = {0x1e,0x10,0x41};
    CHECK(cf_wellformed(v106,3)==1);
    CHECK(c0_canonical(v106,3)==0);
  }
  { /* trailing-eot */
    const unsigned char v107[] = {0x1d,0x67,0x1e,0x61,0x04};
    CHECK(cf_wellformed(v107,5)==1);
    CHECK(c0_canonical(v107,5)==0);
  }
  { /* etb-framing */
    const unsigned char v108[] = {0x1e,0x61,0x17};
    CHECK(cf_wellformed(v108,3)==1);
    CHECK(c0_canonical(v108,3)==0);
  }
  { /* unassigned-code */
    const unsigned char v109[] = {0x1e,0x06};
    CHECK(cf_wellformed(v109,2)==0);
    CHECK(c0_canonical(v109,2)==0);
  }
  { /* dangling-dle */
    const unsigned char v110[] = {0x1e,0x61,0x10};
    CHECK(cf_wellformed(v110,3)==0);
    CHECK(c0_canonical(v110,3)==0);
  }
}

static void cf_invalid(void) {
    const unsigned char v111[] = {0x1e,0x00};
  { /* unassigned-nul */ CHECK(cf_wellformed(v111,2)==0); }
    const unsigned char v112[] = {0x1e,0x06};
  { /* unassigned-ack */ CHECK(cf_wellformed(v112,2)==0); }
    const unsigned char v113[] = {0x1e,0x61,0x18};
  { /* unassigned-can */ CHECK(cf_wellformed(v113,3)==0); }
    const unsigned char v114[] = {0x1e,0x61,0x10};
  { /* dangling-dle */ CHECK(cf_wellformed(v114,3)==0); }
}

static void cf_stream(void) {
  { /* two-commits */
    const unsigned char v115[] = {0x1e,0x61,0x17,0x1e,0x62,0x17};
    c0_stream s = c0_stream_read(v115, 6);
    CHECK(s.committed_end==6);
    CHECK(s.torn==0);
    CHECK(cf_block_count(&s)==2);
    const unsigned char v116[] = {0x1e,0x61};
    CHECK(cf_block_eq(&s,0,v116,2));
    const unsigned char v117[] = {0x1e,0x62};
    CHECK(cf_block_eq(&s,1,v117,2));
    { c0_bytes cm=c0_stream_committed(&s); c0_group g=c0_table(cm.ptr,cm.len); c0_iter ri=c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v118[] = {0x61};
      CHECK(cf_val_eq(rec,0,v118,1));
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v119[] = {0x62};
      CHECK(cf_val_eq(rec,0,v119,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* torn-tail */
    const unsigned char v120[] = {0x1e,0x61,0x17,0x1e,0x62};
    c0_stream s = c0_stream_read(v120, 5);
    CHECK(s.committed_end==3);
    CHECK(s.torn==1);
    CHECK(cf_block_count(&s)==1);
    const unsigned char v121[] = {0x1e,0x61};
    CHECK(cf_block_eq(&s,0,v121,2));
    { c0_bytes cm=c0_stream_committed(&s); c0_group g=c0_table(cm.ptr,cm.len); c0_iter ri=c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v122[] = {0x61};
      CHECK(cf_val_eq(rec,0,v122,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* batch-block */
    const unsigned char v123[] = {0x1e,0x61,0x1e,0x62,0x17};
    c0_stream s = c0_stream_read(v123, 5);
    CHECK(s.committed_end==5);
    CHECK(s.torn==0);
    CHECK(cf_block_count(&s)==1);
    const unsigned char v124[] = {0x1e,0x61,0x1e,0x62};
    CHECK(cf_block_eq(&s,0,v124,4));
    { c0_bytes cm=c0_stream_committed(&s); c0_group g=c0_table(cm.ptr,cm.len); c0_iter ri=c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v125[] = {0x61};
      CHECK(cf_val_eq(rec,0,v125,1));
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v126[] = {0x62};
      CHECK(cf_val_eq(rec,0,v126,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* escaped-etb-not-commit */
    const unsigned char v127[] = {0x1e,0x61,0x10,0x17};
    c0_stream s = c0_stream_read(v127, 4);
    CHECK(s.committed_end==0);
    CHECK(s.torn==1);
    CHECK(cf_block_count(&s)==0);
  }
  { /* etb-in-scope-not-commit */
    const unsigned char v128[] = {0x1e,0x02,0x17,0x03};
    c0_stream s = c0_stream_read(v128, 4);
    CHECK(s.committed_end==0);
    CHECK(s.torn==1);
    CHECK(cf_block_count(&s)==0);
  }
  { /* payload-in-committed-region */
    const unsigned char v129[] = {0x1e,0x61,0x17,0x63,0x61,0x66,0x65};
    c0_stream s = c0_stream_read(v129, 7);
    CHECK(s.committed_end==7);
    CHECK(s.torn==0);
    CHECK(cf_block_count(&s)==1);
    const unsigned char v130[] = {0x1e,0x61};
    CHECK(cf_block_eq(&s,0,v130,2));
    { c0_bytes cm=c0_stream_committed(&s); c0_group g=c0_table(cm.ptr,cm.len); c0_iter ri=c0_group_records(g); c0_bytes rec;
      CHECK(c0_next_record(&ri,&rec));
      CHECK(cf_arity(rec)==1);
      const unsigned char v131[] = {0x61};
      CHECK(cf_val_eq(rec,0,v131,1));
      CHECK(!c0_next_record(&ri,&rec)); }
  }
  { /* empty-stream */
    const unsigned char v132[1] = {0};
    c0_stream s = c0_stream_read(v132, 0);
    CHECK(s.committed_end==0);
    CHECK(s.torn==0);
    CHECK(cf_block_count(&s)==0);
  }
}
